version: '3.8'

services:
  wushi-backend:
    image: crpi-ecp3xwjlx8lx75f1.cn-hangzhou.personal.cr.aliyuncs.com/wushi-space/wushi-backend:v1.0.0
    container_name: wushi-backend-service
    network_mode: "host" # 走 host 模式，让容器共享宿主机的 Tailscale 内网网卡
    environment:
      - DB_HOST=100.97.74.45   # 填入你真实的 MySQL Tailscale 内网 IP
      - DB_USER=root
      - DB_PASSWORD=astock_root
      - CK_HOST=100.97.74.45   # 填入你真实的 ClickHouse Tailscale 内网 IP
      - CK_USER=default
      - CK_PASSWORD=pamirs@123
    restart: always

  wushi-frontend:
    image: crpi-ecp3xwjlx8lx75f1.cn-hangzhou.personal.cr.aliyuncs.com/wushi-space/wushi-frontend:v1.0.0
    container_name: wushi-frontend-service
    ports:
      - "80:80"
    restart: always